[package]
name = "LootBox"
version = "0.0.1"

[dependencies]
Sui = { local = "../sui/crates/sui-framework" }

[dependencies.Movemate]
git = "https://github.com/LoyaltyGM/movemate.git"
subdir = "sui"
# devnet-0.19.0
rev = "180cc00a7cd5b3ac5df23b95f06c610a0fea6ac7"

[addresses]
lootbox = "0x64cf95f363dcb0135625422afbce494a1e703e87"